-- USER TABLES --
CREATE TABLE Users (
user_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
first_Name VARCHAR(20) UNIQUE,
last_Name VARCHAR(20) UNIQUE,
position VARCHAR(20) UNIQUE,
manager_PIN VARCHAR(20) UNIQUE
);
-- PRODUCT TABLES --
CREATE TABLE Milk_Tea (
MT_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
MT_Name VARCHAR(150) UNIQUE,
MT_Medio_Price DECIMAL(4,2) NOT NULL UNIQUE,
MT_Grande_Price DECIMAL(4,2) NOT NULL UNIQUE
);
CREATE TABLE Cold_Coffee (
CC_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
CC_Name VARCHAR(150) UNIQUE,
CC_Medio_Price DECIMAL(4,2) NOT NULL UNIQUE,
CC_Grande_Price DECIMAL(4,2) NOT NULL UNIQUE
);
CREATE TABLE Hot_Coffee (
HC_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
HC_Name VARCHAR(150) UNIQUE,
HC_Price DECIMAL(4, 2) NOT NULL UNIQUE
);
CREATE TABLE Fruit_Tea (
FT_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
FT_Name VARCHAR(150) UNIQUE,
FT_Medio_Price DECIMAL(4,2) NOT NULL UNIQUE,
FT_Grande_Price DECIMAL(4,2) NOT NULL UNIQUE
);
CREATE TABLE Praf (
Praf_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Praf_Name VARCHAR(150) UNIQUE,
Praf_Medio_Price DECIMAL(4,2) NOT NULL UNIQUE,
Praf_Grande_Price DECIMAL(4,2) NOT NULL UNIQUE
);
CREATE TABLE Brosty (
Brosty_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Brosty_Name VARCHAR(150) UNIQUE,
Brosty_Medio_Price DECIMAL(4,2) NOT NULL UNIQUE,
Brosty_Grande_Price DECIMAL(4,2) NOT NULL UNIQUE
);
CREATE TABLE Premiums (
Premium_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
Premium_Name VARCHAR(150) UNIQUE,
Premium_Price DECIMAL(4,2) NOT NULL UNIQUE
);
CREATE TABLE Add_Ons (
Add_OnsID INT PRIMARY KEY NOT NULL,
Add_Ons_Name VARCHAR(100) NOT NULL UNIQUE,
Add_Ons_Price INT(50) NOT NULL UNIQUE
);
-- PWEDE ALISIN ANG UNIQUE SA PRICES KADA TABLES --